# ============================================================
# LOCAL / INTELLIJ
# ============================================================

# H2 database
spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.datasource.url=jdbc:h2:mem:catalogdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Kafka running in Docker, Catalog running in IntelliJ
spring.kafka.bootstrap-servers=localhost:9092

# Consul disabled locally
spring.cloud.consul.discovery.enabled=false
spring.cloud.consul.discovery.register=false
spring.cloud.consul.discovery.catalogServicesWatch.enabled=false
spring.cloud.consul.config.enabled=false

management.health.consul.enabled=false