spring.application.name=VideoGameStoreCatalog
server.port=8081

# Default when pressing Run in IntelliJ
spring.profiles.default=local

# Axon
axon.axonserver.enabled=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Springwolf
springwolf.enabled=false

# MCP Server
spring.ai.mcp.server.name=catalog-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.instructions=This MCP server exposes read-only Catalog tools for listing and searching video games.

spring.ai.mcp.server.capabilities.tool=true
spring.ai.mcp.server.capabilities.resource=false
spring.ai.mcp.server.capabilities.prompt=false
spring.ai.mcp.server.capabilities.completion=false

spring.ai.mcp.server.sse-endpoint=/mcp/sse
spring.ai.mcp.server.sse-message-endpoint=/mcp/messages
