spring.application.name=VideoGameStoreCatalog
server.port=8081

# Default when pressing Run in IntelliJ
spring.profiles.default=local

# Axon
axon.axonserver.enabled=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Springwolf
springwolf.enabled=false