spring.application.name=order-management

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2

axon.axonserver.enabled=false

springwolf.enabled=false
#springwolf.docket.base-package=com.vgs.ordermanagement
#springwolf.docket.info.title=Order Service
#springwolf.docket.info.version=0.0.1-SNAPSHOT
#springwolf.docket.servers.kafka.protocol=kafka
#springwolf.docket.servers.kafka.host=localhost:9092